name: tv_app_wifi
description: A Flutter app for playing RTSP video streams
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.10.1
  socket_io_client: ^2.0.3+1  # For Socket.IO connection
  wakelock_plus: ^1.4.0
  provider: ^6.1.5+1
  app_links: ^6.4.1
  http: ^1.6.0
  flutter_sound: ^9.28.0
  permission_handler: ^12.0.1
  mobile_scanner: ^7.1.3
  fvp: ^0.35.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true